### ISSUE TITLE
the error 

### ISSUE THREAD

**Issue by zhuyinjing** [geekcomputers/Python#163]
```
Traceback (most recent call last):
  File "MitosisDetection_server.py", line 4, in <module>
    import train
  File "/home/workspace/server/train.py", line 3, in <module>
    from keras.models import Sequential
  File "/root/miniconda2/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/root/miniconda2/lib/python2.7/site-packages/keras/activations.py", line 4, in <module>
    from . import backend as K
  File "/root/miniconda2/lib/python2.7/site-packages/keras/backend/__init__.py", line 72, in <module>
    assert _backend in {'theano', 'tensorflow'}
AssertionError
```
what should i do ? 
thanks so much!

**Comment by lolAJhere** [comment]
try changing `import train` to `from . import train`
