### ISSUE TITLE
How do you Make This

### ISSUE THREAD

**Issue by De-Been-Tech-Solutions** [geekcomputers/Python#1677]
How do you make this program? Unless this is a joke.

![unknown_2022 08 22-17 03](https://user-images.githubusercontent.com/60248725/185864937-2574a7f7-dfe4-4bd5-b4e0-5cac3e9aefcd.png)

**Comment by NickDeBeenAIE** [comment]
More like how do you use this?

I double click after installing Python 3.10 and it flashes for a split second and doesn't stay open.

**Comment by NickDeBeenAIE** [comment]
``Traceback (most recent call last):``
  ``File "C:\Users\Nick\Desktop\Python-master\Python-master\insertpythonscripthere.py", line 4, in <module>``
    ``import requests``
``ModuleNotFoundError: No module named 'requests'``

**Comment by NickDeBeenAIE** [comment]
``Traceback (most recent call last):
  File "C:\Users\Nick\Desktop\Python-master\Python-master\facebook id hack.py", line 73, in <module>
    if function(email, passw, i):
  File "C:\Users\Nick\Desktop\Python-master\Python-master\facebook id hack.py", line 47, in function
    payload, cookie = create_form()
  File "C:\Users\Nick\Desktop\Python-master\Python-master\facebook id hack.py", line 39, in create_form
    if data.input["name"] == "lsd":
AttributeError: 'NoneType' object has no attribute 'input'``
