### ISSUE TITLE
can not excute this script

### ISSUE THREAD

**Issue by oxfordyang2016** [geekcomputers/Python#32]
import shownfile#i have named this script
 Enter a file name: r'c:\python27\showfile.py'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\showfile.py", line 18, in <module>
    file_stats = os.stat(file_name)
WindowsError: [Error 123] : "r'c:\\python27\\showfile.py'"

**Comment by palashgoel7** [comment]
Can you post the contents of shownfile? You might not need r in the beginning of your input.

**Comment by ab-anand** [comment]
No need for mentioning r in the start. Simply do this 'c:\python27\showfile.py'.
For more info on this method hit here: [os.stat()](https://www.tutorialspoint.com/python/os_stat.htm)

**Comment by cclauss** [comment]
Can this issue be closed?
