### ISSUE TITLE
When a run the youtube.py error occurred

### ISSUE THREAD

**Issue by AprilYoungs** [geekcomputers/Python#360]
Here's the result
```
Young:Desktop Young$ python youtube.py 
Enter the song to be played: Hello
<div class="yt-thumb video-thumb"><span class="yt-thumb-simple">
<img alt="" data-ytimg="1" height="138" onload=";window.__ytRIL &amp;&amp; __ytRIL(this)" src="//i1.ytimg.com/vi/HeLjGn8OLnU/mqdefault.jpg" width="246"/>
<span aria-hidden="true" class="video-time">3:59</span></span></div>
Traceback (most recent call last):
  File "youtube.py", line 29, in <module>
    link = song['href']
  File "/Users/Young/anaconda3/lib/python3.6/site-packages/bs4/element.py", line 1011, in __getitem__
    return self.attrs[key]
KeyError: 'href'

```

It seems the youtube has change the result structure and don't have a 'href' anymore

**Comment by kushagra189** [comment]
I would like to solve the same @AprilYoungs . But it says permission denied when I tried to make a push via new branch(for creating a merge request).

**Comment by kushagra189** [comment]
#367  was made. Please look into it. @AprilYoungs

**Comment by AprilYoungs** [comment]
I've try your new code,but still get the same error.

**Comment by kushagra189** [comment]
Works fine on my machine. What error is it showing?
![1](https://user-images.githubusercontent.com/23234327/45630715-d844c580-bab6-11e8-9b31-42642cc2ffa6.png)

**Comment by AprilYoungs** [comment]
I run the code on the MacOS,maybe the html is different from OS

**Comment by kushagra189** [comment]
Any other way to resolve the same?

**Comment by AprilYoungs** [comment]
Work as expected today.
Maybe  my network is not good,will you add this code 
```
try:
    link = song['href']
    webbrowser.open('https://www.youtube.com' + link)
except KeyError:
    print("Can't find any song,check your network or try a new word")
```

**Comment by kushagra189** [comment]
added.
