### ISSUE TITLE
New to python had a problem

### ISSUE THREAD

**Issue by Satya-SriRam-Varma** [geekcomputers/Python#476]
hello,everyone I was having time to learn python so i started learning it from day before yesterday,now I am trying to make snake game from curses module and I ran into A TROUBLE, figured someone from here would lend me some of their experience regarding this 

class Snake(object):
    def _init_(self):
        self.x='Hiss!'

    def method_a(self,foo):
        print(self.x +' '+ foo)

snake = Snake()
snake.method_a('Says the snake')

the above code fragment is having an error
upon trying to run it the terminal gives the following

Traceback (most recent call last):
  File "hc.py", line 31, in <module>
    snake.method_a('Says the snake')#passing foo as argument
  File "hc.py", line 28, in method_a
    print(self.x +' '+ foo)
AttributeError: 'Snake' object has no attribute 'x'

can't find where the error is so i request you guys to please help me if you know any thing regarding this

**Comment by Satya-SriRam-Varma** [comment]
and sorry for some reason github is not allowing me to put UNDERSCORE before and after init

**Comment by AronYang** [comment]
Please replace 'init'  to '__init__'.

**Comment by AronYang** [comment]
replace 'init'  with  `__init__`

**Comment by AronYang** [comment]
I see your picture. that is `_init_`.  the correct is `__init__`

**Comment by Satya-SriRam-Varma** [comment]
Thank you AronYang

**Comment by HoreeChen** [comment]
good eye！

**Comment by Abhi050** [comment]
"""This is my first help in the open source  or first comment """
Replace init by __init__
the two underscores before and after init

**Comment by ANDREW-LAMICHHANE** [comment]
Hey your code:
class Snake(object):
	def init(self):
		self.x='Hiss!'
	def method_a(self,foo):
	print(self.x +' '+ foo)

snake = Snake()
snake.method_a('Says the snake')

Mistakes:
#1 init --> __init__
#2 __init__  ---> it initializes code variable , so any code inside it is global i.e restricited to itself and not 
                         availabe to method_a
#3 var x has not been made in the instance i.e ---> [def__init__(self, x):]--> corrrect code
#4 if you make x global within __init__, you will get this message: <SyntaxError: name 'x' is local and global>

My code:
class Snake():
	global x
	x='Hiss!'
	def method_a(self,foo):
		print(x +' '+ foo)

snake = Snake()
snake.method_a('Says the snake')

I hope the answer helps you.

**Comment by ANDREW-LAMICHHANE** [comment]
Hey your code:
class Snake(object):
def init(self):
self.x='Hiss!'
def method_a(self,foo):
print(self.x +' '+ foo)

snake = Snake()
snake.method_a('Says the snake')

Mistakes:
#1 init --> __init__
#2 init ---> it initializes code variable , so any code inside it is global i.e restricted to itself and not
availabe to method_a
#3 var x has not been made in the instance i.e ---> [def__init__(self, x):]--> corrrect code
#4 if you make x global within init, you will get this message: <SyntaxError: name 'x' is local and global>

My code:
class Snake():
global x
x='Hiss!'
def method_a(self,foo):
print(x +' '+ foo)

snake = Snake()
snake.method_a('Says the snake')

I hope the answer helps you.

**Comment by ANDREW-LAMICHHANE** [comment]
Hey your code:
class Snake(object):
def init(self):
self.x='Hiss!'
def method_a(self,foo):
print(self.x +' '+ foo)

snake = Snake()
snake.method_a('Says the snake')

Mistakes:
#1 init --> <__init__>
#2 init ---> it initializes code variable , so any code inside it is global i.e restricited to itself and not
availabe to method_a
#3 var x has not been made in the instance i.e ---> [def__init__(self, x):]--> corrrect code
#4 if you make x global within init, you will get this message: <SyntaxError: name 'x' is local and global>

My code:
class Snake():
global x
x='Hiss!'
def method_a(self,foo):
print(x +' '+ foo)

snake = Snake()
snake.method_a('Says the snake')

I hope the answer helps you.

**Comment by makcmoscow** [comment]
> Mistakes:
> #1 init --> <**init**>
> #2 init ---> it initializes code variable , so any code inside it is global i.e restricited to itself and not
> availabe to method_a
REALLY????


> My code:
> class Snake():
> global x

Global variables are evil! Never do like this...

**Comment by Unknow-gui** [comment]
give you a thubs up

**Comment by lkkplau0988** [comment]
I copy it to run on python first,I don't know the error

**Comment by MarvinKweyu** [comment]
Can you be more specific @ikkplau0988?

**Comment by lkkplau0988** [comment]
I try to run the program again,thanks
