### ISSUE TITLE
How to test the nslookup script?

### ISSUE THREAD

**Issue by thinhduckhoi** [geekcomputers/Python#49]
Here's the content of server.txt file under /root/python folder i put in with the nslookup script.
google.com
bbc.co.uk
Is this correct?

If so, the script didn't work.
I tested this script on python 2.6.6 and this error appeared.
Traceback (most recent call last):
  File "nslookup_check.py", line 4, in <module>
    subprocess.Popen(('nslookup '+server))
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

In case of python 3.4
Traceback (most recent call last):
  File "nslookup_check.py", line 4, in <module>
    subprocess.Popen(('nslookup '+server))
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/subprocess.py", line 1456, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'nslookup google.com\n'

.

**Comment by munendrasn** [comment]
@thinhduckhoi 
I too got the same error. This is caused due to
```
subprocess.Popen(('nslookup '+server))
```
According to Popen Class, First argument must be `sequence`, here it is `string`

It must be
```
subprocess.Popen(['nslookup', server])
```

For more information, go through the documentation - https://docs.python.org/2/library/subprocess.html

I have pull request #48  with required changes. Please let me know, If it solves your error.

**Comment by thinhduckhoi** [comment]
@munendrasn Thanks you! It worked!
