### ISSUE TITLE
ModuleNotFoundError: No module named 'win32api

### ISSUE THREAD

**Issue by nishikeshKardak** [geekcomputers/Python#621]
While running `cricket_live_score.py` it throws the following error. Even if the module is already installed.
#### Error Message: 
```
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\test.py", line 4, in <module>
    from win10toast import ToastNotifier
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win10toast\__init__.py", line 19, in <module>
    from win32api import GetModuleHandle
ModuleNotFoundError: No module named 'win32api
```

#### Installed Module: 
```
C:\Users\Admin>pip install pywin32
Requirement already satisfied: pywin32 in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages (225)
```

**Comment by XxPro1445GamerxX** [comment]
Try pip install pypiwin32 instead.

**Comment by nishikeshKardak** [comment]
The package is already installed.
```
C:\Users\Admin>pip install pypiwin32
Requirement already satisfied: pypiwin32 in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages (223)
Requirement already satisfied: pywin32>=223 in c:\users\admin\appdata\local\programs\python\python37-32\lib\site-packages (from pypiwin32) (225)
```

**Comment by mohantyabhijit074** [comment]
try to run 
pip install pywin32
and in conda
conda install pywin32
