### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mert679** [geekcomputers/Python#923]
I have a trouble
Traceback (most recent call last):
  File "C:/Users/merta/PycharmProjects/pythonProject1/0example.py", line 7, in <module>
    root.resizable("0,0")
  File "C:\Users\merta\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 2196, in wm_resizable
    return self.tk.call('wm', 'resizable', self._w, width, height)
_tkinter.TclError: wrong # args: should be "wm resizable window ?width height?"

**Comment by CodeLongAndProsper90** [comment]
Try using `root.resizable(0,0)`?

**Comment by mert679** [comment]
import time
from tkinter import *

root=Tk()
root.title("digital clock")
root.geometry("250x100")
root.resizable("0,0")
label = Label(root, font=("Arial", 30, 'bold'), bg="blue", fg="powder blue", bd =30)
label.grid(row =0, column=1)

def dig_clock():
    text_input = time.strftime("%H:%M:%S")
    label.config(text=text_input)
    label.after(200,dig_clock)

dig_clock()
root.mainloop()
